"""votes_table_added

Revision ID: 886ea6fb53d6
Revises: da8af33dafed
Create Date: 2022-07-12 05:41:17.546911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886ea6fb53d6'
down_revision = 'da8af33dafed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('answerId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Boolean(), nullable=False),
    sa.Column('createTime', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['answerId'], ['answers.answerId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answerId', 'userId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
